name: influxdb-configurable
version: '1.8.3'
base: core18
architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: arm64
    run-on: arm64
    
summary: InfluxDB timeseries database
description: |

    InfluxDB is an open source time series platform. This includes APIs for storing and querying data, processing it in the background for ETL or monitoring and alerting purposes,
    user dashboards, and visualizing and exploring the data and more. The master branch on this repo now represents the latest InfluxDB, which now includes functionality for Kapacitor 
    (background processing) and Chronograf (the UI) all in a single binary.


confinement: strict

apps:
    
    influxd:
        command: bin/runinfluxd.sh
        daemon: simple
        plugs: [network, network-bind]
        restart-condition: always
        environment:
          INFLUXDB_META_DIR: $SNAP_COMMON/meta
          INFLUXDB_DATA_DIR: $SNAP_COMMON/data
          INFLUXDB_DATA_WAL_DIR: $SNAP_COMMON/wal
          INFLUXDB_CONFIG_PATH: $SNAP_COMMON/conf/influxdb.conf
          INFLUXD_BOLT_PATH: $SNAP_COMMON/influxdbv2/influxd.bolt
          INFLUXD_ENGINE_PATH: $SNAP_COMMON/influxdbv2/engine

    influx:
        command: usr/bin/influx
        plugs: [network, network-bind]
        
    info:
        command: bin/info.sh 
        plugs: [network, network-bind]

        

parts:

    
    influxdb:
        plugin: dump
        source:
         - on amd64: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.3_amd64.deb
         - on arm64: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.3_arm64.deb
        stage-packages:
            - libssl1.1
            - libcurl3-dev
            - libcurl4-openssl-dev

  
    shscripts:  
        source: ./shscripts/
        plugin: dump
        organize:
          '*': bin/
